name: confidence_openfeature_provider_example
description: Confidence OpenFeature mobile example.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  confidence_openfeature_provider:
    path: ../
  openfeature_dart_client_sdk: 0.0.1-beta.1
dev_dependencies:
  lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
