name: confidence_flutter_sdk
description: "Flutter implementation of the Confidence SDK."
version: 0.2.4
homepage: https://confidence.spotify.com

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  uuid: ^4.0.0
  path_provider: ^2.1.0
  device_info_plus: ^10.0.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
