name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: macos-latest

    env:
      FLUTTER_CHANNEL: stable
      FLUTTER_VERSION: 3.22.2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: fetch submodules
      run: git submodule update --init --recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - name: Setup Pub Credentials
      shell: bash
      env:
            PUB_ACCESS_TOKEN: ${{ secrets.PUB_ACCESS_TOKEN }}
            PUB_REFRESH_TOKEN: ${{ secrets.PUB_REFRESH_TOKEN }}
            PUB_TOKEN_ENDPOINT: ${{ secrets.PUB_TOKEN_ENDPOINT }}
            PUB_EXPIRATION: ${{ secrets.PUB_EXPIRATION }}
      run: |
            sh ./pub_login.sh
    - name: Check Publish Warnings
      run: |
            flutter pub publish --dry-run
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - name: Install dependencies
      working-directory: example
      run: flutter pub get

    - name: Build Android
      working-directory: example
      run: flutter build apk --release

    - name: Copy iOS
      working-directory: ios/Classes
      run: cp -r confidence-sdk/Sources/Confidence .

    - name: Remove the submodule
      working-directory: ios/Classes
      run: rm -rf confidence-sdk

    - name: Remove git submodule
      working-directory: ios/Classes
      run: git rm confidence-sdk

    - name: Build iOS
      working-directory: example
      run: flutter build ios --release --no-codesign

