name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLUTTER_CHANNEL: stable
      FLUTTER_VERSION: 3.27.3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - run: echo API_KEY=${{ secrets.TEST_API_KEY }} > example/.env

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze
      run: flutter analyze

    - name: Run tests
      run: flutter test
