name: Dart provider

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/confidence_openfeature_provider
    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.12.2'
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed lib test
      - run: dart analyze --fatal-infos
      - run: dart test
