name: Test-iOS
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  ios-test:
    runs-on: macos-latest

    env:
      FLUTTER_CHANNEL: stable
      FLUTTER_VERSION: 3.27.3

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: fetch submodules
        run: git submodule update --init --recursive

      - name: Copy iOS
        working-directory: ios/Classes
        run: cp -r confidence-sdk/Sources/Confidence .

      - name: Remove the submodule
        working-directory: ios/Classes
        run: rm -rf confidence-sdk

      - name: Remove git submodule
        working-directory: ios/Classes
        run: git rm confidence-sdk

      - uses: futureware-tech/simulator-action@bfa03d93ec9de6dacb0c5553bbf8da8afc6c2ee9 # v3
        with:
          model: 'iPhone 16'

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - run: echo API_KEY=${{ secrets.TEST_API_KEY }} > example/.env
      - run: cd example && flutter drive --driver=test_drive/integration_test.dart --target=test/widget_test.dart
